### ISSUE TITLE
Why RAG?

### ISSUE THREAD

**Issue by avesus** [run-llama/rags#35]
What is and _why_ one needs a RAG?

**Comment by Ts4587** [comment]
what is rag, and what is the use of rag

**Comment by anoopshrma** [comment]
I recently came towards this article explaining the need of RAG and sort of RAG 101. 
https://gradient.ai/blog/rag-101-for-enterprise

I think this can help you both!!

**Comment by HugoPereir** [comment]
4cbf5338609c0124420e189378280428b5ed4cff09d96c93798bfb38d857b5d7

**Comment by HugoPereir** [comment]
3c9f5735837033b85fc463b33e25127542af04b82c343e65f76e8e7e2549f79d

**Comment by HugoPereir** [comment]
Hugo
