### ISSUE TITLE
Error during running answer to Home page

### ISSUE THREAD

**Issue by snassimr** [run-llama/rags#5]
Hi, 

I am getting this error during submitting an answer to "What RAG bot do you want to build?" question : 

![image](https://github.com/run-llama/rags/assets/6830626/f87dd5d2-f866-4998-b992-1b82af114395)

I guess it relates to openai credentials . What do you mean : "Please .streamlit/secrets.toml in the home folder." 

Is "home" folder is "rags" folder - the roor folder of repo or home folder of host machine ?

**Comment by jerryjliu** [comment]
yeah home folder is rags folder, so path from parent directory of that would be `rags/.streamlit/secrets.toml` 

it's also possible openai api is just down
