### ISSUE TITLE
"Update Agent" creates an error and deletes the Agent

### ISSUE THREAD

**Issue by sorcery-ai** [run-llama/rags#53]
After creating an agent and navigating to "RAG Config" for the purpose of selecting the checkbox labeled "Include Summarization (only works for GPT-4)" an error is produced and the Agent is deleted after clicking "Update Agent".

Error:
![image](https://github.com/run-llama/rags/assets/133713208/90d3a231-d324-4406-a3dd-70d573fc6dfa)

**Comment by sorcery-ai** [comment]
The only way I have been able to get this to work is by asking for it to:

```Please "Include Summarization" for this agent.```

However when the browser is refreshed, it reverts to an unchecked state.

**Comment by brandedux** [comment]
![image](https://github.com/run-llama/rags/assets/32825782/6baabb4a-2024-4322-b933-36ec9a8461f2)

**Comment by nickknyc** [comment]
> The only way I have been able to get this to work is by asking for it to:
> 
> `Please "Include Summarization" for this agent.`
> 
> However when the browser is refreshed, it reverts to an unchecked state.

Just to be sure - are you sure that your openai key is loaded up and that when you make your change you are hitting the update button
![image](https://github.com/run-llama/rags/assets/1598572/643184d7-3852-4d60-85b6-e64d31af5ce6)

**Comment by sorcery-ai** [comment]
That isn't/wasn't the issue, however this seems to have been fixed in the latest update.
