### ISSUE TITLE
[ENH] can we use azure openai endpoints?

### ISSUE THREAD

**Issue by alexfilothodoros** [run-llama/rags#55]
Hi.

What would be needed in order to use azure openai endpoints?
I think some changes in utils/_resolve_llm are certainly needed?

Any advice? I'd like to work on this topic, but I was thinking that someone else might have alreadt thought about that and could provide some feedback.

Cheers

**Comment by ChrisDelClea** [comment]
+1

**Comment by ravi03071991** [comment]
You can check the documentation on [Azure OpenAI](https://docs.llamaindex.ai/en/stable/examples/llm/azure_openai.html) for which we have already an integration and can be used straightforwardly.
